// <auto-generated />
using System;
using Andes.Agents.Repository.Sql.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Andes.Agents.Repository.Sql.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260912044531_CreateSessionReportingTables")]
    partial class CreateSessionReportingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Andes.Agents.Entity.Agents.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Agent", "Core.Ref");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34f1c4ff-6232-4001-8c45-3cfa859144e9"),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "weather-agent",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("Andes.Agents.Entity.Agents.AgentModelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.HasIndex("ModelId");

                    b.HasIndex("AgentId", "DateCreated");

                    b.ToTable("AgentModelMapping", "Core.Ref", t =>
                        {
                            t.HasCheckConstraint("CK_AgentModelMapping_ActivationWindow", "[DateDeactivated] IS NULL OR [DateDeactivated] >= [DateCreated]");
                        });
                });

            modelBuilder.Entity("Andes.Agents.Entity.Agents.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CachedInputPricePerMillionTokens")
                        .HasPrecision(19, 9)
                        .HasColumnType("decimal(19,9)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("InputPricePerMillionTokens")
                        .HasPrecision(19, 9)
                        .HasColumnType("decimal(19,9)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OutputPricePerMillionTokens")
                        .HasPrecision(19, 9)
                        .HasColumnType("decimal(19,9)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentName")
                        .IsUnique();

                    b.ToTable("Model", "Core.Ref", t =>
                        {
                            t.HasCheckConstraint("CK_Model_Prices", "[InputPricePerMillionTokens] >= 0 AND [CachedInputPricePerMillionTokens] >= 0 AND [OutputPricePerMillionTokens] >= 0");
                        });
                });

            modelBuilder.Entity("Andes.Agents.Entity.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CoverageAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HolderReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal>("PremiumAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("HolderReference");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("HolderReference"), new[] { "PolicyNumber", "Status", "EffectiveDate", "ExpirationDate" });

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("Status", "ExpirationDate");

                    b.ToTable("Policy", "Core", t =>
                        {
                            t.HasCheckConstraint("CK_Policy_CoverageAmount", "[CoverageAmount] > 0");

                            t.HasCheckConstraint("CK_Policy_CoverageWindow", "[ExpirationDate] > [EffectiveDate]");

                            t.HasCheckConstraint("CK_Policy_CurrencyCode", "[CurrencyCode] COLLATE Latin1_General_100_BIN2 LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_Policy_PremiumAmount", "[PremiumAmount] >= 0");

                            t.HasCheckConstraint("CK_Policy_Status", "[Status] COLLATE Latin1_General_100_BIN2 IN ('Draft', 'Active', 'Lapsed', 'Cancelled', 'Expired')");
                        });
                });

            modelBuilder.Entity("Andes.Agents.Entity.Sessions.SessionSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CachedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(19, 9)
                        .HasColumnType("decimal(19,9)");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("ReasoningTokens")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("DateCreated");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId", "SessionId", "DateCreated")
                        .IsUnique();

                    b.ToTable("Session", "Core", t =>
                        {
                            t.HasCheckConstraint("CK_Session_Counts", "[MessageCount] >= 0 AND [InputTokens] >= 0 AND [CachedInputTokens] >= 0 AND [OutputTokens] >= 0 AND [ReasoningTokens] >= 0 AND [TotalTokens] >= 0");

                            t.HasCheckConstraint("CK_Session_EstimatedCost", "[EstimatedCost] >= 0");
                        });
                });

            modelBuilder.Entity("Andes.Agents.Entity.Agents.AgentModelMapping", b =>
                {
                    b.HasOne("Andes.Agents.Entity.Agents.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Andes.Agents.Entity.Agents.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Andes.Agents.Entity.Sessions.SessionSummary", b =>
                {
                    b.HasOne("Andes.Agents.Entity.Agents.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Andes.Agents.Entity.Agents.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
