<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Andes.Agents.Dto\Andes.Agents.Dto.csproj" />
    <ProjectReference Include="..\Andes.Agents.Entity\Andes.Agents.Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
